# Qui êtes-vous ?
<div class="alert alert-block alert-info">
Écrire ci-dessous le nom, le prénom et le numéro étudiant de chaque membre du binôme :
</div>

# TME 06X - Variables discrètes

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

## 1 - Manipulation d'une loi de probabilité jointe

<div class="alert alert-block alert-warning">
Soit deux variables aléatoires $X$ et $Y$ qui suivent la loi de probabilité jointe suivante :
$$
    \begin{array}{c|cccc}
      p_{XY}(x, y) & 0 & 1 & 2 & 3 \\
      \hline
      0 & \frac{9}{32} & \frac{3}{32} & \frac{1}{32} & \frac{7}{32} \\
      1 & \frac{1}{32} & \frac{2}{32} & \frac{8}{32} & \frac{1}{32}
    \end{array}
$$
</div>

<div class="alert alert-block alert-info">
Q1.1 - Déclarer un tableau <code>pxy</code> représentant cette loi de probabilité jointe.
</div>

In [35]:
pxy = [
    [9/32, 3/32, 1/32, 7/32],
    [1/32, 2/32, 8/32, 1/32]
]

pxy = np.array(pxy)
pxy

array([[ 0.28125,  0.09375,  0.03125,  0.21875],
       [ 0.03125,  0.0625 ,  0.25   ,  0.03125]])

<div class="alert alert-block alert-info">
Q1.2 - Écrire une fonction <code>est_proba</code> qui prend en paramètre un tableau numpy et qui renvoie <code>True</code> s'il s'agit d'une loi de probabilité jointe (et <code>False</code> sinon).
    
On vérifira que chaque valeur est comprise entre 0 et 1 et que la somme vaut 1 (à $\epsilon$ près si nécessaire).
</div>

In [22]:
def est_proba(tab):
    return all(0 <= x and x <= 1 for y in tab for x in y) and np.sum(tab) == 1

est_proba(pxy)

True

<div class="alert alert-block alert-warning">
On rappelle qu'on peut accéder à des sous-parties d'un tableau numpy avec la syntaxe suivante (pour <code>pxy</code>) :
<ul>
    <li><code>pxy[1, 2]</code> renvoie la donnée située à la ligne 1 et à la colonne 2</li>
    <li><code>pxy[0:2, 2]</code> renvoie toute la colonne 2</li>
    <li><code>pxy[0, 0:4]</code> renvoie toute la ligne 0</li>
</ul>
</div>

<div class="alert alert-block alert-info">
Q1.3 - Calculer la loi marginale de $X$ dans un tableau <code>px</code>.
</div>

In [24]:
px = np.sum(pxy, axis = 1)
est_proba([px])

True

<div class="alert alert-block alert-info">
Q1.4 - Calculer la loi marginale de $Y$ dans un tableau <code>py</code>.
</div>

In [25]:
py = np.sum(pxy, axis = 0)
est_proba([py])

True

<div class="alert alert-block alert-info">
Q1.5 - Calculer la loi $p_X \times p_y$ dans un tableau <code>pxpy</code>.
</div>

In [31]:
pxpy = np.dot(px.reshape((2, 1)), py.reshape((4, 1)).T)
pxpy

array([[ 0.1953125 ,  0.09765625,  0.17578125,  0.15625   ],
       [ 0.1171875 ,  0.05859375,  0.10546875,  0.09375   ]])

<div class="alert alert-block alert-info">
Q1.6 - $X$ et $Y$ sont-elles indépendantes ?
</div>

In [38]:
# La loi jointe et la loi produit ne sont pas les mêmes donc les variables sont dépendantes
(pxpy == pxy).all()

False

<div class="alert alert-block alert-info">
Q1.7 - Écrire une fonction qui prend en paramètre un tableau représentant une loi de probabilité jointe de deux variables aléatoires discrètes et qui renvoie <code>True</code> si ces variables sont indépendantes (et <code>False</code> sinon).
</div>

In [39]:
def indep(pxy):
    px = np.sum(pxy, axis = 1)
    py = np.sum(pxy, axis = 0)
    pxpy = np.dot(px.reshape((2, 1)), py.reshape((4, 1)).T)
    return (pxpy == pxy).all()

False

<div class="alert alert-block alert-info">
Q1.8 - Écrire une instruction qui teste votre fonction sur <code>pxy</code> et sur <code>pxpy</code>.
</div>

In [41]:
indep(pxy), indep(pxpy)

(False, True)

## 2 - Probablités conditionnelles

<div class="alert alert-block alert-warning">
Dans cette partie, nous allons continuer de travailler avec la loi jointe <code>pxy</code>.
</div>

<div class="alert alert-block alert-info">
Q2.1 - Calculer la loi conditionnelle $p_{X|Y}(x)$ dans un tableau <code>pxSy</code>.
</div>

In [45]:
pxSy = np.array([ pxy[:, i] / pyi for i, pyi in enumerate(py) ]).T
pxSy

array([[ 0.9       ,  0.6       ,  0.11111111,  0.875     ],
       [ 0.1       ,  0.4       ,  0.88888889,  0.125     ]])

<div class="alert alert-block alert-info">
Q2.2 - De même, calculer la loi conditionnelle $p_{Y|X}(y)$ dans un tableau <code>pySx</code>.
</div>

In [46]:
pySx = np.array([ pxy[i, :] / pxi for i, pxi in enumerate(px) ])
pySx

array([[ 0.45      ,  0.15      ,  0.05      ,  0.35      ],
       [ 0.08333333,  0.16666667,  0.66666667,  0.08333333]])

<div class="alert alert-block alert-info">
Q2.3 - Chaque calcul précédent permet-il de dire si les variables $X$ et $Y$ sont indépendantes ?
</div>

## 3 - Espérance et variance

<div class="alert alert-block alert-warning">
Nous allons supposer que les réalisations de la variable $X$ correspondent aux indices de lignes et que les réalisations de la variable $Y$ correspondent aux indices de colonnes.
</div>

<div class="alert alert-block alert-info">
Q3.1 - Écrire une fonction <code>esperance</code> qui calcule l'espérance d'une variable aléatoire dont la loi <code>p</code> est donnée sous la forme d'un tableau numpy unidimensionnel.
</div>

In [53]:
def esperance(p):
    return sum(i*pi for i, pi in enumerate(p))

esperance(px)

0.375

<div class="alert alert-block alert-info">
Q3.2 - Calculer l'espérance de la variable $Y$.
</div>

In [54]:
esperance(py)

1.46875

<div class="alert alert-block alert-info">
Q3.3 - Calculer les espérances conditionnelles de $Y$ sachant $X = x$ pour $0 \leqslant x < 2$.
</div>

In [57]:
[*map(esperance, pySx)]

[1.2999999999999998, 1.75]

<div class="alert alert-block alert-warning">
Nous allons à présent calculer des espérances sur la loi jointe. Pour cela, nous passerons en paramètres une fonction de $x$ et de $y$ qui renvoie un réel.
    
Par exemple, nous allons commencer par calculer l'espérance de $X + Y$.
</div>

<div class="alert alert-block alert-info">
Exécuter le bloc suivant qui définit la fonction <code>fsom</code>.
</div>

In [58]:
def fsom(x, y):
    return x + y

<div class="alert alert-block alert-info">
Q3.4 - Écrire une fonction <code>esperance_jointe</code> prend en paramètres une loi jointe de deux variables <code>p</code> et une fonction de deux variables <code>f</code> et qui calcule l'espérance de $f(X, Y)$.
</div>

In [60]:
def esperance_jointe(p, f):
    return sum(f(x, y) * pxy for x, line in enumerate(p) for y, pxy in enumerate(line))

<div class="alert alert-block alert-info">
Q3.5 - Calculer $\mathbb{E}(X + Y)$.
</div>

In [64]:
esperance_jointe(pxy, fsom)

1.84375

<div class="alert alert-block alert-info">
Q3.6 - Calculer $\mathbb{E}(XY)$.
</div>

In [65]:
from operator import mul # x,y -> xy
esperance_jointe(pxy, mul)

0.65625

<div class="alert alert-block alert-info">
Q3.7- Écrire une fonction <code>covariance</code> prend en paramètres une loi jointe de deux variables <code>p</code> et qui renvoie la covariance de $X$ et $Y$.
</div>

In [68]:
def covariance(p):
    return esperance_jointe(p, mul) - esperance(p.sum(axis=1)) * esperance(p.sum(axis=0))

<div class="alert alert-block alert-info">
Q3.8 - Calculer $\mathbb{C}ov(X, Y)$.
</div>

In [70]:
covariance(pxy)

0.10546875